version: "3.1"
services:
  pg:
      build: .
      ports:
        - "5432:5432"
      tty: true
      restart: always
      stdin_open: true
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      volumes:
        - "./data:/var/lib/postgresql/data"
